[workspace]
resolver = "3"
members = [ "bittorrent_offload", "rdr_client_cache", "rdr_common", "rdr_parent_cache", "tls_validator", "video_transcoder"]

[workspace.package]
version = "0.1.0"
edition = "2024"
